# Generated by Django 5.2.7 on 2025-11-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=100)),
                ('experience', models.TextField(blank=True, null=True)),
                ('education', models.TextField(max_length=200)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('appllied_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
