# Generated by Django 5.2.7 on 2025-11-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appliocations',
            new_name='Application',
        ),
    ]
